-- +goose Up
INSERT INTO VENDOR VALUES(1, 'John Wick');
INSERT INTO VENDOR VALUES(2, 'Peter Parker');
INSERT INTO VENDOR VALUES(3, 'Kratos');
INSERT INTO VENDOR VALUES(4, 'VendorMan');
INSERT INTO VENDOR VALUES(5, 'Zoro');
INSERT INTO VENDOR VALUES(6, 'Dr. Alam');
INSERT INTO VENDOR VALUES(7, 'Crash Bandicoot');
INSERT INTO VENDOR VALUES(8, 'Lebron James');

INSERT INTO INVENTORY_CATEGORY VALUES(1, 'Tableware');
INSERT INTO INVENTORY_CATEGORY VALUES(2, 'Furniture');
INSERT INTO INVENTORY_CATEGORY VALUES(3, 'Ingredients');
INSERT INTO INVENTORY_CATEGORY VALUES(4, 'Miscellaneous');

INSERT INTO INVENTORY_SUBCATEGORY VALUES(1,1, 'Forks');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(2,1, 'Spoons');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(3,2, 'Tables');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(4,2, 'Chairs');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(5,3, 'Spices');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(6,3, 'Meats');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(7,4, 'Plumbing');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(8,4, 'OfficeSupplies');

INSERT INTO FOOD_VENDOR VALUES(1);
INSERT INTO FOOD_VENDOR VALUES(2);
INSERT INTO FOOD_VENDOR VALUES(3);
INSERT INTO FOOD_VENDOR VALUES(4);

INSERT INTO NONFOOD_VENDOR VALUES(5);
INSERT INTO NONFOOD_VENDOR VALUES(6);
INSERT INTO NONFOOD_VENDOR VALUES(7);
INSERT INTO NONFOOD_VENDOR VALUES(8);

INSERT INTO SUPPLY VALUES(1, 'Steel Forks', 7500, 750, 1, 6);
INSERT INTO SUPPLY VALUES(2, 'Dining Tables', 150, 15, 3, 8);
INSERT INTO SUPPLY VALUES(3, 'Chili Powder', 963, 30, 5, 4);
INSERT INTO SUPPLY VALUES(4, 'Printer Paper', 15632, 150, 8, 5);

INSERT INTO PROMOTION VALUES (1, 'New Year New Deals', 'Sale for the New Years holiday', 5.00, '2024-December-27', '2025-January-04');
INSERT INTO PROMOTION VALUES(2, 'Spooky SZN', 'Sale, for the week OF Halloween', 4.99, '23-October-2024', '31-October-2024');
INSERT INTO PROMOTION VALUES(3, 'Spring Break', 'Sale for Spring Break', 4.98, '21-March-2024', '28-March-2024');
INSERT INTO PROMOTION VALUES(4, 'Christmas Sale', 'Sale for week of Christmas', 5.01, '18-December-2024', '25-December-2024');
INSERT INTO PROMOTION VALUES(5, 'Managers Special', 'Sale because the manager said so', 4.97, '22-September-2024', '22-September-2024');

INSERT INTO HOLIDAYS_RECOGNIZED VALUES(1, 'New Years Day', '01-January-2025');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(2, 'Halloween', '31-October-2024');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(3, 'Peak of SpringBreak', '25-March -2024');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(4, 'Christmas Day', '25-December-2024');

INSERT INTO HOLIDAY_PROMOTION VALUES (1,1);
INSERT INTO HOLIDAY_PROMOTION VALUES (2,2);
INSERT INTO HOLIDAY_PROMOTION VALUES (3,3);
INSERT INTO HOLIDAY_PROMOTION VALUES (4,4);

INSERT INTO MANAGERS_SPECIAL VALUES (5);

INSERT INTO FOOD_CATEGORY VALUES (1, 'Pizzas');
INSERT INTO FOOD_CATEGORY VALUES (2, 'Appetizers');
INSERT INTO FOOD_CATEGORY VALUES (3, 'Salads');
INSERT INTO FOOD_CATEGORY VALUES (4, 'Drinks');
INSERT INTO FOOD_CATEGORY VALUES (5, 'Sides');

INSERT INTO FOOD_SUBCATEGORY VALUES (1, 'Classic Pizzas', 1);
INSERT INTO FOOD_SUBCATEGORY VALUES (2, 'Specialty Pizzas', 1);
INSERT INTO FOOD_SUBCATEGORY VALUES (3, 'Breadsticks', 2 );
INSERT INTO FOOD_SUBCATEGORY VALUES (4, 'Wings', 2);
INSERT INTO FOOD_SUBCATEGORY VALUES (5, 'Garlic Knots', 2);
INSERT INTO FOOD_SUBCATEGORY VALUES (6, 'Garden Salads', 3);
INSERT INTO FOOD_SUBCATEGORY VALUES (7, 'Caesar Salads', 3);
INSERT INTO FOOD_SUBCATEGORY VALUES (8, 'Soft Drink', 4);

INSERT INTO FOOD_ITEM VALUES (1, 'Pepperoni Pizza', 'Small', 100, 8.99, 1);
INSERT INTO FOOD_ITEM VALUES (2, 'Cheese Pizza', 'Medium', 100, 10.99, 1);
INSERT INTO FOOD_ITEM VALUES (3, 'Hawaiian Pizza', 'Large', 100, 12.99, 2);
INSERT INTO FOOD_ITEM VALUES (4, 'Meat Lover Pizza', 'Large', 100, 12.99, 2);
INSERT INTO FOOD_ITEM VALUES (5, 'Garlic Knots with Marinara Sauce', 'Reg', 100, 5.49, 5);
INSERT INTO FOOD_ITEM VALUES (6, 'Buffalo Wings', '10 pcs', 100, 9.99, 4);
INSERT INTO FOOD_ITEM VALUES (7, 'Garden Salad', 'Reg', 100, 6.49, 6);
INSERT INTO FOOD_ITEM VALUES (8, 'Caesar Salad', 'Reg', 100, 8.49, 6);
INSERT INTO FOOD_ITEM VALUES (9, 'Coca-Cola', '12 oz', 100, 8.49, 8);
INSERT INTO FOOD_ITEM VALUES (10, 'Plain Breadsticks', 'Reg', 100, 8.49, 2);

INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,1, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,2, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,3, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,4, 0);
-- +goose StatementBegin
SELECT 'up SQL query';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
