-- +goose Up
INSERT INTO VENDOR VALUES(1, 'John Wick');
INSERT INTO VENDOR VALUES(2, 'Peter Parker');
INSERT INTO VENDOR VALUES(3, 'Kratos');
INSERT INTO VENDOR VALUES(4, 'VendorMan');
INSERT INTO VENDOR VALUES(5, 'Zoro');
INSERT INTO VENDOR VALUES(6, 'Dr. Alam');
INSERT INTO VENDOR VALUES(7, 'Crash Bandicoot');
INSERT INTO VENDOR VALUES(8, 'Lebron James');

INSERT INTO INVENTORY_CATEGORY VALUES(1, 'Tableware');
INSERT INTO INVENTORY_CATEGORY VALUES(2, 'Furniture');
INSERT INTO INVENTORY_CATEGORY VALUES(3, 'Ingredients');
INSERT INTO INVENTORY_CATEGORY VALUES(4, 'Miscellaneous');

INSERT INTO INVENTORY_SUBCATEGORY VALUES(1,1, 'Forks');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(2,1, 'Spoons');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(3,2, 'Tables');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(4,2, 'Chairs');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(5,3, 'Spices');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(6,3, 'Meats');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(7,4, 'Plumbing');
INSERT INTO INVENTORY_SUBCATEGORY VALUES(8,4, 'OfficeSupplies');

INSERT INTO FOOD_VENDOR VALUES(1);
INSERT INTO FOOD_VENDOR VALUES(2);
INSERT INTO FOOD_VENDOR VALUES(3);
INSERT INTO FOOD_VENDOR VALUES(4);

INSERT INTO NONFOOD_VENDOR VALUES(5);
INSERT INTO NONFOOD_VENDOR VALUES(6);
INSERT INTO NONFOOD_VENDOR VALUES(7);
INSERT INTO NONFOOD_VENDOR VALUES(8);

INSERT INTO SUPPLY VALUES(1, 'Steel Forks', 7500, 750, 1, 6);
INSERT INTO SUPPLY VALUES(2, 'Dining Tables', 150, 15, 3, 8);
INSERT INTO SUPPLY VALUES(3, 'Chili Powder', 963, 30, 5, 4);
INSERT INTO SUPPLY VALUES(4, 'Printer Paper', 15632, 150, 8, 5);

INSERT INTO PROMOTION VALUES (1, 'New Year New Deals', 'Sale for the New Years holiday', 5.00, '2024-December-27', '2025-January-04');
INSERT INTO PROMOTION VALUES(2, 'Spooky SZN', 'Sale, for the week OF Halloween', 4.99, '23-October-2024', '31-October-2024');
INSERT INTO PROMOTION VALUES(3, 'Spring Break', 'Sale for Spring Break', 4.98, '21-March-2024', '28-March-2024');
INSERT INTO PROMOTION VALUES(4, 'Christmas Sale', 'Sale for week of Christmas', 5.01, '18-December-2024', '25-December-2024');
INSERT INTO PROMOTION VALUES(5, 'Managers Special', 'Sale because the manager said so', 4.97, '22-September-2024', '22-September-2024');

INSERT INTO HOLIDAYS_RECOGNIZED VALUES(1, 'New Years Day', '01-January-2025');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(2, 'Halloween', '31-October-2024');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(3, 'Peak of SpringBreak', '25-March -2024');
INSERT INTO HOLIDAYS_RECOGNIZED VALUES(4, 'Christmas Day', '25-December-2024');

INSERT INTO HOLIDAY_PROMOTION VALUES (1,1);
INSERT INTO HOLIDAY_PROMOTION VALUES (2,2);
INSERT INTO HOLIDAY_PROMOTION VALUES (3,3);
INSERT INTO HOLIDAY_PROMOTION VALUES (4,4);

INSERT INTO MANAGERS_SPECIAL VALUES (5);

INSERT INTO FOOD_CATEGORY VALUES (1, 'Pizzas');
INSERT INTO FOOD_CATEGORY VALUES (2, 'Appetizers');
INSERT INTO FOOD_CATEGORY VALUES (3, 'Salads');
INSERT INTO FOOD_CATEGORY VALUES (4, 'Drinks');
INSERT INTO FOOD_CATEGORY VALUES (5, 'Sides');

INSERT INTO FOOD_SUBCATEGORY VALUES (1, 'Classic Pizzas', 1);
INSERT INTO FOOD_SUBCATEGORY VALUES (2, 'Specialty Pizzas', 1);
INSERT INTO FOOD_SUBCATEGORY VALUES (3, 'Breadsticks', 2);
INSERT INTO FOOD_SUBCATEGORY VALUES (4, 'Wings', 2);
INSERT INTO FOOD_SUBCATEGORY VALUES (5, 'Garlic Knots', 2);
INSERT INTO FOOD_SUBCATEGORY VALUES (6, 'Garden Salads', 3);
INSERT INTO FOOD_SUBCATEGORY VALUES (7, 'Caesar Salads', 3);
INSERT INTO FOOD_SUBCATEGORY VALUES (8, 'Soft Drink', 4);

INSERT INTO FOOD_ITEM VALUES (1, 'Pepperoni Pizza', 'Small', 100, 8.99, 1);
INSERT INTO FOOD_ITEM VALUES (2, 'Cheese Pizza', 'Medium', 100, 10.99, 1);
INSERT INTO FOOD_ITEM VALUES (3, 'Hawaiian Pizza', 'Large', 100, 12.99, 2);
INSERT INTO FOOD_ITEM VALUES (4, 'Meat Lover Pizza', 'Large', 100, 12.99, 2);
INSERT INTO FOOD_ITEM VALUES (5, 'Garlic Knots with Marinara Sauce', 'Reg', 100, 5.49, 5);
INSERT INTO FOOD_ITEM VALUES (6, 'Buffalo Wings', '10 pcs', 100, 9.99, 4);
INSERT INTO FOOD_ITEM VALUES (7, 'Garden Salad', 'Reg', 100, 6.49, 6);
INSERT INTO FOOD_ITEM VALUES (8, 'Caesar Salad', 'Reg', 100, 8.49, 7);
INSERT INTO FOOD_ITEM VALUES (9, 'Coca-Cola', '12 oz', 100, 8.49, 8);
INSERT INTO FOOD_ITEM VALUES (10, 'Plain Breadsticks', 'Reg', 100, 8.49, 3);

INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,1, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,2, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,3, 0);
INSERT INTO PROMOTION_FOOD_BRIDGE VALUES (1,4, 0);

INSERT INTO ROLE VALUES (1, 'Cashier', 1, 10.00);

INSERT INTO ROLE VALUES (2, 'Cook', 1, 12.00);

INSERT INTO ROLE VALUES (3, 'Manager', 0, 50000.00);

INSERT INTO EMPLOYEE VALUES (1, NULL, 1, 'John', 'Doe', '123 Main St', 'Anytown', 'CA', '12345', '1990-01-01', 10.00);

INSERT INTO EMPLOYEE VALUES (2, 1, 2, 'Jane', 'Smith', '456 Oak St', 'Othertown', 'NY', '54321', '1992-05-15', 12.00);

INSERT INTO EMPLOYEE VALUES (3, 1, 3, 'John', 'Smith', '456 Oak St', 'Othertown', 'NY', '54321', '1993-06-12', 55000);

INSERT INTO SHIFT VALUES (1, '08:00:00', '16:00:00');

INSERT INTO SHIFT VALUES (2, '12:00:00', '20:00:00');

INSERT INTO EMPLOYEE_SHIFT_BRIDGE VALUES (1, 1, 8.00, '2024-04-19 08:00:00', '2024-04-19 16:00:00');

INSERT INTO EMPLOYEE_SHIFT_BRIDGE VALUES (2, 2, 7.50, '2024-04-19 12:00:00', '2024-04-19 19:30:00');

INSERT INTO JOB_HISTORY VALUES (1, 1, '2022-01-01', '2023-01-01', 10.00);

INSERT INTO JOB_HISTORY VALUES (2, 2, '2023-03-15', '2023-06-11', 12.00);

INSERT INTO CHEF VALUES (2, 'Italian Cuisine');

INSERT INTO CERTIFICATION VALUES ('C1','Food Safety', 'Health and Safety');

INSERT INTO CERTIFICATION VALUES (1, 'Food Safety', 'Health and Safety');

INSERT INTO CHEF_CERT_BRIDGE VALUES (1, 2, '2025-01-01');

INSERT INTO MANAGER VALUES (1, 'Store Manager');

INSERT INTO DEGREE VALUES (1, 'Bachelor of Business Administration', 'Business', 'University of X', '2020-05-15');

INSERT INTO MANAGER_DEGREE_BRIDGE (DEGREE_ID, EMPLOYEE_ID) VALUES (1, 3);

INSERT INTO CLUB_CARD VALUES (1, 0);

INSERT INTO CUSTOMER VALUES (1, 'John', 'Test', '123 Address Rd', 'Somewhere', 'Alabama', '99999', '1993-01-02', 1, NULL);

INSERT INTO ORDER_METHOD VALUES (1, 'Site');

INSERT INTO ORDER_METHOD VALUES (2, 'Phone');

INSERT INTO ORDER_METHOD VALUES (3, 'In Store');

INSERT INTO PAYMENT_METHOD VALUES (1, 'Cash');

INSERT INTO PAYMENT_METHOD VALUES (2, 'Credit Card');

INSERT INTO PAYMENT_METHOD VALUES (3, 'Debit Card')

INSERT INTO PAYMENT_METHOD VALUES (4, 'PayPal');

INSERT INTO ORDERS VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP, NULL)

INSERT INTO ORDER_DETAIL VALUES (1, 1, NULL, 1, 1, NULL, 10.00, 0.00)

INSERT INTO ORDER_STATUS VALUES (1, 'Making');

INSERT INTO ORDER_STATUS VALUES (2, 'Baking');

INSERT INTO ORDER_STATUS VALUES (3, 'Preparing');

INSERT INTO ORDER_STATUS VALUES (4, 'On The Way');

INSERT INTO ORDER_STATUS VALUES (5, 'Completed');

INSERT INTO ORDER_STATUS_BRIDGE VALUES (1, 5, 1);
-- +goose StatementBegin
SELECT 'up SQL query';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
